-- AlterTable
ALTER TABLE "Depenses" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "heure" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "RevenuMensuelle" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;
